#!/usr/bin/env node

/**
 * MoltStream CLI
 * AI-native streaming infrastructure
 *
 * Usage:
 *   npx moltstream init     - Interactive setup wizard
 *   npx moltstream start    - Start streaming with config
 *   npx moltstream status   - Check pipeline status
 */

import { Command } from 'commander';
import { writeFile, readFile, access } from 'fs/promises';
import { join } from 'path';
import * as readline from 'readline';

const VERSION = '0.7.0';
const CONFIG_FILE = 'moltstream.yaml';

const program = new Command();

program
  .name('moltstream')
  .description('AI-native streaming infrastructure — one command to go live')
  .version(VERSION);

// ─── INIT ───

program
  .command('init')
  .description('Interactive setup wizard — creates moltstream.yaml')
  .action(async () => {
    console.log(`
  ╔══════════════════════════════════════╗
  ║     ⚡ MoltStream v${VERSION}            ║
  ║     AI-native streaming infra        ║
  ╚══════════════════════════════════════╝
`);

    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    const ask = (q: string, def?: string): Promise<string> =>
      new Promise((resolve) => {
        const suffix = def ? ` (${def})` : '';
        rl.question(`  ${q}${suffix}: `, (answer: string) => {
          resolve(answer.trim() || def || '');
        });
      });

    try {
      console.log('  Let\'s set up your AI streamer.\n');

      const agentName = await ask('Agent name', 'MoltBot');
      const platform = await ask('Platform (kick/youtube/twitch)', 'kick');
      const channel = await ask(`${platform.charAt(0).toUpperCase() + platform.slice(1)} channel slug`);

      console.log('');
      const personality = await ask(
        'Agent personality',
        'A witty, engaging AI streamer who loves tech and gaming'
      );

      console.log('\n  --- API Keys ---\n');
      const llmProvider = await ask('LLM provider (gemini/anthropic)', 'gemini');
      const llmKey = await ask(`${llmProvider === 'gemini' ? 'Gemini' : 'Anthropic'} API key`);
      const ttsProvider = await ask('TTS provider (fish/elevenlabs/openai)', 'fish');
      const ttsKey = await ask(`${ttsProvider} API key`);

      console.log('\n  --- Streaming ---\n');
      const kickToken = await ask('Kick auth token (for sending chat messages, optional)');
      const avatarEnabled = await ask('Enable avatar? (yes/no)', 'yes');
      const broadcastEnabled = await ask('Enable FFmpeg broadcast? (yes/no)', 'yes');
      let rtmpUrl = '';
      let streamKey = '';
      if (broadcastEnabled.toLowerCase().startsWith('y')) {
        rtmpUrl = await ask('RTMP URL', 'rtmps://fa723fc1b171.global-contribute.live-video.net/');
        streamKey = await ask('Stream Key');
      }

      // Generate config
      const config = `# MoltStream Configuration
# Generated by moltstream init

agent:
  name: "${agentName}"
  personality: "${personality}"

platform:
  type: "${platform}"
  channel: "${channel}"
  ${kickToken ? `authToken: "${kickToken}"` : '# authToken: "" (optional, for sending chat messages)'}

llm:
  provider: "${llmProvider}"
  apiKey: "${llmKey}"
  model: "${llmProvider === 'gemini' ? 'gemini-2.5-flash' : 'claude-sonnet-4-20250514'}"
  maxTokens: 200

tts:
  provider: "${ttsProvider}"
  apiKey: "${ttsKey}"
  # voice: "" (optional, uses default)

avatar:
  enabled: ${avatarEnabled.toLowerCase().startsWith('y')}
  port: 3939
  backgroundColor: "#00FF00"

broadcast:
  enabled: ${broadcastEnabled.toLowerCase().startsWith('y')}
  rtmpUrl: "${rtmpUrl}"
  streamKey: "${streamKey}"
  width: 1920
  height: 1080
  fps: 30
  bitrate: 4500

stream:
  cooldownSeconds: 5
  respondEveryN: 1
`;

      const configPath = join(process.cwd(), CONFIG_FILE);
      await writeFile(configPath, config);

      console.log(`
  ✅ Config saved to ${CONFIG_FILE}

  Next steps:
    1. Run: moltstream start
    2. Add OBS Browser Source: http://localhost:3939
    3. Set OBS RTMP to your ${platform} stream key
    4. Go live!

  Docs: https://github.com/skaggsxyz/moltstream
`);
    } finally {
      rl.close();
    }
  });

// ─── START ───

program
  .command('start')
  .description('Start the AI streamer pipeline')
  .option('-c, --config <path>', 'Config file path', CONFIG_FILE)
  .action(async (opts: { config: string }) => {
    const configPath = join(process.cwd(), opts.config);

    try {
      await access(configPath);
    } catch {
      console.error(`\n  ✗ Config not found: ${opts.config}`);
      console.error(`  Run 'moltstream init' first.\n`);
      process.exit(1);
    }

    const raw = await readFile(configPath, 'utf-8');
    const config = parseYamlSimple(raw);

    console.log(`
  ╔══════════════════════════════════════╗
  ║     🔴 MoltStream v${VERSION}            ║
  ║     Starting ${(config.agent?.name || 'MoltBot').padEnd(22)}║
  ╚══════════════════════════════════════╝
`);

    // Validate required fields
    if (!config.platform?.channel) {
      console.error('  ✗ Missing platform.channel in config');
      process.exit(1);
    }
    if (!config.llm?.apiKey) {
      console.error('  ✗ Missing llm.apiKey in config');
      process.exit(1);
    }

    // Dynamic import to avoid loading everything at startup
    const { MoltStreamer } = await import('@moltstream/streamer');

    const streamer = new MoltStreamer({
      channel: config.platform.channel,
      llmProvider: (config.llm?.provider || 'gemini') as 'gemini' | 'anthropic',
      apiKey: config.llm.apiKey,
      kickAuthToken: config.platform?.authToken,
      agentName: config.agent?.name ?? 'MoltBot',
      personality: config.agent?.personality ?? 'A friendly AI streamer',
      model: config.llm?.model ?? (config.llm?.provider === 'anthropic' ? 'claude-sonnet-4-20250514' : 'gemini-2.5-flash'),
      maxTokens: Number(config.llm?.maxTokens ?? 200),
      cooldownSeconds: Number(config.stream?.cooldownSeconds ?? 5),
      respondEveryN: Number(config.stream?.respondEveryN ?? 1),
      tts: config.tts?.apiKey ? {
        provider: config.tts.provider as any,
        apiKey: config.tts.apiKey,
        voice: config.tts.voice,
      } : undefined,
      avatar: config.avatar?.enabled !== false ? {
        enabled: true,
        port: Number(config.avatar?.port ?? 3939),
        backgroundColor: config.avatar?.backgroundColor ?? '#00FF00',
      } : undefined,
      broadcast: config.broadcast?.enabled && config.broadcast.rtmpUrl && config.broadcast.streamKey ? {
        enabled: true,
        rtmpUrl: config.broadcast.rtmpUrl,
        streamKey: config.broadcast.streamKey,
        width: Number(config.broadcast.width ?? 1920),
        height: Number(config.broadcast.height ?? 1080),
        fps: Number(config.broadcast.fps ?? 30),
        bitrate: Number(config.broadcast.bitrate ?? 4500),
      } : undefined,
    });

    // Graceful shutdown
    process.on('SIGINT', () => { streamer.stop(); process.exit(0); });
    process.on('SIGTERM', () => { streamer.stop(); process.exit(0); });

    await streamer.start();

    // Auto-configure OBS if broadcast config exists
    if (config.broadcast?.enabled && config.broadcast.rtmpUrl && config.broadcast.streamKey) {
      console.log('\n  📡 Configuring OBS via WebSocket...');
      try {
        const obsOk = await setupOBS(config.broadcast.rtmpUrl, config.broadcast.streamKey);
        if (obsOk) {
          console.log('  ✅ OBS configured and streaming!');
        } else {
          console.log('  ⚠ OBS not detected. Start OBS manually and add Browser Source: http://localhost:3939');
        }
      } catch {
        console.log('  ⚠ Could not connect to OBS WebSocket. Start OBS manually.');
        console.log('    1. Open OBS');
        console.log('    2. Add Browser Source → http://localhost:3939');
        console.log('    3. Settings → Stream → Custom → paste your RTMP URL + key');
        console.log('    4. Start Streaming');
      }
    }
  });

// ─── STATUS ───

program
  .command('status')
  .description('Check if moltstream is configured and ready')
  .action(async () => {
    const configPath = join(process.cwd(), CONFIG_FILE);
    try {
      await access(configPath);
      const raw = await readFile(configPath, 'utf-8');
      const config = parseYamlSimple(raw);

      console.log(`
  MoltStream Status
  ─────────────────
  Config:    ✅ ${CONFIG_FILE}
  Agent:     ${config.agent?.name || '(unnamed)'}
  Platform:  ${config.platform?.type || '?'} / ${config.platform?.channel || '?'}
  LLM:       ${config.llm?.provider || '?'} (${config.llm?.model || '?'})
  TTS:       ${config.tts?.apiKey ? '✅ ' + config.tts.provider : '❌ not configured'}
  Avatar:    ${config.avatar?.enabled !== false ? '✅ port ' + (config.avatar?.port || 3939) : '❌ disabled'}
  Broadcast: ${config.broadcast?.enabled && config.broadcast.rtmpUrl ? '✅ to ' + config.broadcast.rtmpUrl.slice(0, 20) + '...' : '❌ disabled'}
`);
    } catch {
      console.log(`
  MoltStream Status
  ─────────────────
  Config:    ❌ Not found
  Run 'moltstream init' to get started.
`);
    }
  });

// ─── DOCTOR (preflight check) ───

program
  .command('doctor')
  .description('Check system requirements')
  .action(async () => {
    console.log(`
  MoltStream Doctor
  ─────────────────`);

    // Node version
    const nodeVer = process.version;
    const nodeMajor = parseInt(nodeVer.slice(1));
    console.log(`  Node.js:   ${nodeMajor >= 18 ? '✅' : '❌'} ${nodeVer} ${nodeMajor < 18 ? '(need 18+)' : ''}`);

    // OBS
    const { execSync } = await import('child_process');
    let obsOk = false;
    try {
      const obsPath = execSync('which obs 2>/dev/null || ls /Applications/OBS.app 2>/dev/null', { encoding: 'utf-8' });
      obsOk = obsPath.trim().length > 0;
    } catch {}
    console.log(`  OBS:       ${obsOk ? '✅ installed' : '❌ not found (brew install --cask obs)'}`);

    // FFmpeg
    let ffmpegOk = false;
    try {
      execSync('which ffmpeg', { encoding: 'utf-8' });
      ffmpegOk = true;
    } catch {}
    console.log(`  FFmpeg:    ${ffmpegOk ? '✅ installed' : '⚠ not found (optional)'}`);

    // Config
    const configPath = join(process.cwd(), CONFIG_FILE);
    let configOk = false;
    try {
      await access(configPath);
      configOk = true;
    } catch {}
    console.log(`  Config:    ${configOk ? '✅ ' + CONFIG_FILE : '❌ run: npx moltstream init'}`);

    console.log('');
  });

program.parse();

// ─── OBS WebSocket auto-setup ───

async function setupOBS(rtmpUrl: string, streamKey: string): Promise<boolean> {
  // Try connecting to OBS WebSocket (port 4455)
  return new Promise((resolve) => {
    const timeout = setTimeout(() => resolve(false), 5000);

    // @ts-ignore
    import('ws').then((wsModule: any) => {
      const WS = wsModule.default || wsModule;
      const ws = new WS('ws://localhost:4455');

      ws.on('error', () => {
        clearTimeout(timeout);
        resolve(false);
      });

      ws.on('open', () => {
        // OBS WebSocket v5 protocol — identify
        ws.on('message', async (data: any) => {
          try {
            const msg = JSON.parse(data.toString());

            if (msg.op === 0) {
              // Hello — send Identify
              ws.send(JSON.stringify({ op: 1, d: { rpcVersion: 1 } }));
            }

            if (msg.op === 2) {
              // Identified — now configure stream
              // Set stream service settings
              ws.send(JSON.stringify({
                op: 6,
                d: {
                  requestType: 'SetStreamServiceSettings',
                  requestId: 'set-stream',
                  requestData: {
                    streamServiceType: 'rtmp_custom',
                    streamServiceSettings: {
                      server: rtmpUrl,
                      key: streamKey,
                    },
                  },
                },
              }));

              // Start streaming
              ws.send(JSON.stringify({
                op: 6,
                d: {
                  requestType: 'StartStream',
                  requestId: 'start-stream',
                  requestData: {},
                },
              }));

              clearTimeout(timeout);
              setTimeout(() => {
                ws.close();
                resolve(true);
              }, 2000);
            }
          } catch {}
        });
      });
    }).catch(() => {
      clearTimeout(timeout);
      resolve(false);
    });
  });
}

// ─── Simple YAML parser (no deps) ───

function parseYamlSimple(text: string): any {
  const result: any = {};
  let currentSection = '';

  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const sectionMatch = trimmed.match(/^(\w+):$/);
    if (sectionMatch) {
      currentSection = sectionMatch[1];
      result[currentSection] = result[currentSection] || {};
      continue;
    }

    const kvMatch = trimmed.match(/^(\w+):\s*(.+)$/);
    if (kvMatch && currentSection) {
      let value: any = kvMatch[2].trim();
      // Remove quotes
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      // Booleans
      if (value === 'true') value = true;
      if (value === 'false') value = false;
      // Numbers
      if (/^\d+$/.test(value)) value = parseInt(value, 10);

      result[currentSection][kvMatch[1]] = value;
    }
  }

  return result;
}
